version: "3.8"
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=8000
      - DB_CONN=mysql+pymysql://root:password@mysql:3306/database
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - loader
  frontend:
    build:
      context: ./client/
      dockerfile: Dockerfile
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - loader
      - backend
  loader:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    environment:
      - DB_CONN=mysql+pymysql://root:password@mysql:3306/database
    command: python load.py
    depends_on:
      - mysql
