version: "3.8"
services:
    mysql:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: database
    backend:
        build:
            context: ./
            dockerfile: Dockerfile
        environment: 
            - PORT=8000
            - DB_CONN=mysql+pymysql://root:password@mysql:3306/database
        ports:
            - "8000:8000"
        depends_on: 
            - mysql
            - loader
    frontend:
        build:
            context: ./
            dockerfile: Dockerfile-frontend
        environment: 
            - PORT=4000
        ports:
            - "80:4000"
        depends_on: 
            - mysql
            - loader
            - backend
    loader:
        build:
            context: ./
            dockerfile: Dockerfile
        environment: 
            - DB_CONN=mysql+pymysql://root:password@mysql:3306/database
        command: python load.py
        depends_on: 
            - mysql